export const QUERY_KEYS = {
  APPROVED_HOURLY_SIGNAL        : 'APPROVED_HOURLY_SIGNAL',
  HOURLY_EQUITY_DECISION_STATUS : 'HOURLY_EQUITY_DECISION_STATUS',
  HOURLY_EQUITY_DECISION_STATUS_BY_SYMBOL:
    'HOURLY_EQUITY_DECISION_STATUS_BY_SYMBOL',
  HOURLY_EQUITY_BUY_SELL_GRAPHIC_BY_SYMBOL:
    'HOURLY_EQUITY_BUY_SELL_GRAPHIC_BY_SYMBOL',
  HOURLY_EQUITY_SPEEDMETER_GRAPHIC_BY_SYMBOL:
    'HOURLY_EQUITY_SPEEDMETER_GRAPHIC_BY_SYMBOL',
  HOURLY_EQUITY_DECISION_STRATEGY_PERFORMANCE:
    'HOURLY_EQUITY_DECISION_STRATEGY_PERFORMANCE',
  HOURLY_EQUITY_CUMULATIVE_RETURN_BY_SYMBOL:
    'HOURLY_EQUITY_CUMULATIVE_RETURN_BY_SYMBOL',
  HOURLY_EQUITY_HOURLY_RETURN_BY_SYMBOL:
    'HOURLY_EQUITY_HOURLY_RETURN_BY_SYMBOL',
  HOURLY_EQUITY_DRAWDOWN_BY_SYMBOL: 'HOURLY_EQUITY_DRAWDOWN_BY_SYMBOL',
  DASHBOARD_HOURLY_EQUITY_DECISION_STATUS:
    'DASHBOARD_HOURLY_EQUITY_DECISION_STATUS',
  GET_CUSTOMER_INFO                : 'GET_CUSTOMER_INFO',
  PAIR_DAILY_SIGNALS               : 'PAIR_DAILY_SIGNALS',
  PAIR_DAILY_SIGNALS_BY_SYMBOL     : 'PAIR_DAILY_SIGNALS_BY_SYMBOL',
  PAIR_DAILY_SIGNALS_P1_GRAPHIC    : 'PAIR_DAILY_SIGNALS_P1_GRAPHIC',
  PAIR_DAILY_SIGNALS_T1_GRAPHIC    : 'PAIR_DAILY_SIGNALS_T1_GRAPHIC',
  PAIR_DAILY_SIGNALS_P2_GRAPHIC    : 'PAIR_DAILY_SIGNALS_P2_GRAPHIC',
  PAIR_DAILY_SIGNALS_T2_GRAPHIC    : 'PAIR_DAILY_SIGNALS_T2_GRAPHIC',
  DAILY_SCANNING_SIGNALS           : 'DAILY_SCANNING_SIGNALS',
  DAILY_SCANNING_SIGNALS_BY_SYMBOL : 'DAILY_SCANNING_SIGNALS_BY_SYMBOL',
  DAILY_SCANNING_GRAPHIC           : 'DAILY_SCANNING_GRAPHIC',
} as const;
