import Head from 'next/head';

import useAsyncLocalization from '@libs/hooks/useAsyncLocalization';

const Wrapper = ({ children }) => {
  const { isLoading } = useAsyncLocalization(true);

  return (
    <>
      <Head>
        <title>Pratik Öneri</title>
        <meta content='Generated by create next app' name='description' />
        <meta content='width=device-width, initial-scale=1' name='viewport' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <main>{isLoading ? null : children}</main>
    </>
  );
};

export default Wrapper;
